### ISSUE TITLE
Missing license information

### ISSUE THREAD

**Issue by he29-net** [bencikpeter/3DPrintingProtocols#1]
Hi Peter,
if you want to allow other people to use, modify or distribute your work, you need to pick a license for the software you developed. If you want to use a very permissive license as you mentioned earlier, I suggest you take a look at the short and simple MIT License (https://choosealicense.com/licenses/mit/) or the more specific and "modern" Apache License 2.0 (https://choosealicense.com/licenses/apache-2.0/).

There is an interesting article explaining in more detail why it is important to include a license etc., if you are interested: https://blog.codinghorror.com/pick-a-license-any-license/

**Comment by bencikpeter** [comment]
Hello,
Thank's for the notice. The software is now licensed under MIT Licence.
